### ISSUE TITLE
The data format

### ISSUE THREAD

**Issue by rs-dl** [hoel-bagard/PyTorch-Video-Classification#2]
Great codes! Could you provide the data format for this project?

or, Could you provide your format of "labels.json"?

Many thanks!

**Comment by hoel-bagard** [comment]
Hi,
This project is still under development but thanks for checking it out. It is developed for a defect classification project where the defects are not always visible on the video. It probably contains a fair amount of parameters hard coded for that one specific project. I would not mind trying to make it more general, but in its current form it is unlikely to be what you're looking for.

Here is the data format for this project:


## Dataset structure
<p align="center">
  <img src="https://user-images.githubusercontent.com/34478245/100103177-e61cdf00-2ea7-11eb-971c-59813940a975.png">
</p>

## classes.names
The classes.names file is expect to be a simple text file with one class name per line.
Example:
```
cat
dog
car
```

## labels.json
It is created using the `label_video.py` script.
Each entry contains a path to a video and a list of the time stamps. Each time stamp corresponds to a frame where the class changes from classX to "not_visible"

Example:
```
{
    "entries": [
        {
            "file_path": "class1/subfolder1/video-0.mp4",
            "time_stamps": [
                0
            ]
        },
        {
            "file_path": "class1/subfolder2/video-1.mp4",
            "time_stamps": [
                110,
                116,
                250
            ]        },
        {
            "file_path": "class3/subfolder1/video-2.mp4",
            "time_stamps": []
        }
    ]
}
```

<p align="right">
    <a href="../wiki/Video-Classification">Next page</a>
</p>
